config/routes.rb
ObtuseSharkHunters::Application.routes.draw do
  resources :customers

  get "customer/index"

  get "customer/show"

  get "user_views/index"

  get "user_views/show"

  get "product_user/index"

  get "product_user/show"

  resources :categories

  resources :orders

  resources :products
  
  resources :pages
  
  
  
  match '/about' => 'product_user#about'
  match '/contact' => 'product_user#contact'
  
  match '/productuser' => 'user_views#index', :as => 'user_view'
  match '/productshow/:id' => 'user_views#show', :as => 'detail', :via => :get
  match '/customers' => 'customers#index'
  
  root:to => 'product#index'
  
    

end

app/controllers/user_views_controller.rb
class UserViewsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/user_views_helper.rb
module UserViewsHelper
end

app/views/user_views/_user_views.html.erb

<div>
    <hr/>
    <%=image_tag product.img_url, :width => '100', :align => "left", :hspace => '15'%>
    <h3><%= product.name %></h3>
<p><b><u>Description :</u></b>
    <%= product.description %></p>
</div>
<br/>
<br/>
   <br/>
    <p>Quantity On Hand: <%= product.quantity %>,
                  Price $<%= product.price %></p>
    <%= link_to 'Add To Cart' %>
    <hr/>
</div>
    <%= link_to 'View Full Product Detail', detail_path(product) %>
<br />

app/views/user_views/index.html.erb
<%=image_tag 'SHARK05.jpg', :width => '100', :align => "left", :hspace => '15'%>
<h1>All Obtuse Shark Hunting Products</h1>
<%= link_to 'About Obtuse Shark Hunters Incorporated', about_path%>
<%= link_to 'Contact Us', contact_path%>
<br/>
<br/>
<%= render :partial => 'user_views', :collection => @products, :as => 'product' %>

app/views/user_views/show.html.erb
<div>
    <h3><%= @product.name %></h3>
    <hr/>
   <%=image_tag @product.img_url, :width => '100', :align => "left", :hspace => '35'%>
</div>
<div>
<p><b><u>Description :</u></b></p>
 <p id="move_over"><%= @product.description %></p>
</div>
<br/>
<br/>
<div>
   <br/>
    <p>Quantity On Hand: <%= @product.quantity %>,
                  Price $<%= @product.price %></p>
    <hr/>
</div>
<%= link_to 'Back To All Products', user_view_path%>
<br />