config/routes.rb
ObtuseSharkHunters::Application.routes.draw do
  resources :customers

  get "customer/index"

  get "customer/show"

  get "user_views/index"

  get "user_views/show"

  get "product_user/index"

  get "product_user/show"

  resources :categories

  resources :orders

  resources :products
  
  resources :pages
  
  
  
  match '/about' => 'product_user#about'
  match '/contact' => 'product_user#contact'
  
  match '/productuser' => 'user_views#index', :as => 'user_view'
  match '/productshow/:id' => 'user_views#show', :as => 'detail', :via => :get
  match '/customers' => 'customers#index'
  
  root:to => 'product#index'
  
    

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<%=image_tag 'SHARK05.jpg', :width => '100', :align => "left", :hspace => '0'%>
<h2><%= page.title %></h2>
<div><%= page.body%></div>


<p>Created on <%= page.created_at %></p>
<p>Last Updated <%= page.updated_at %></p>



app/views/pages/about.html.erb
<%=image_tag 'SHARK05.jpg', :width => '100', :align => "left", :hspace => '0'%>
<h1>Obtuse Shark Hunters Incorporated</h1>
<hr/>
<br/>
<p>Obtuse Shark Hunters Incorporated started out as a pipe dream of two young entrepenuers.
Their dream was that the  shark hunting population of winnipeg would no longer  have to rely on the shady service of American companies.

They began their dream by opening their first franchise in their beloved city, and soon people from across canada were flocking to their store for the latest and greatest gear.

Over the last years, Obtuse Shark Hunters Incorporated has grown to franchises in each province , with distribution across canada, providing a trustable company to handle your shark problems.

We invite you to check out our store, 
</p>
<%= link_to 'View Our Products', products_path %>

app/views/pages/contact.html.erb
<%=image_tag 'SHARK05.jpg', :width => '100', :align => "left", :hspace => '0'%>
<h1> Contact Information</h1>
<hr/>

<h3>Locations:</h3>
<p><b>Winnipeg,Manitoba, </b>900 Portage Avenue R5P 9L2</p>
<p><b>Victoria, British Cloumbia </b>123 Go Street</p>
<p><b>Edmonton, Alberta </b>456 Trent Ave</p>
<p><b>Prince Edward Island, </b>900 Cavendish Rd</p>
<p><b>Ottawa, Ontario </b>400 McArthur Ave</p>

<h3>Business Hours:</h3>
<p><b>Mon-Fri: </b>9:30 A.M - 7:00 P.M</p>
<p><b>Sat: </b>9:30 A.M - 5:30 P.M</p>
<p><b>Sun: </b>12:00 A.M - 5:30 P.M</p>

<h3>Online Support Hours: </h3>
<p><b>24 hours a day, 365 Days a year</b></p>



<%= link_to 'View Our Products', products_path %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render :partial => 'form' %>

|
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Admin Page Editing Menu</h1>
<br/>
<br/>


<% @pages.each do |page| %>
  
   <h2> <%= page.title %> </h2>
   <br/>
    <%= page.body %>
    <br/><br/>
    <%= link_to 'Show', page %>
    <%= link_to 'Edit', edit_page_path(page) %>
    <%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %>
  <% end %>


<br />

<%= link_to 'New Page', new_page_path %>
<!-- future link for products area -->

app/views/pages/new.html.erb
<h1>Create A page</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back to All Posts', pages_path %>

app/views/pages/show.html.erb
<%= render @page %>

<%= link_to 'Back', pages_path %>