config/routes.rb
ObtuseSharkHunters::Application.routes.draw do
  resources :customers

  get "customer/index"

  get "customer/show"

  get "user_views/index"

  get "user_views/show"

  get "product_user/index"

  get "product_user/show"

  resources :categories

  resources :orders

  resources :products
  
  resources :pages
  
  
  
  match '/about' => 'product_user#about'
  match '/contact' => 'product_user#contact'
  
  match '/productuser' => 'user_views#index', :as => 'user_view'
  match '/productshow/:id' => 'user_views#show', :as => 'detail', :via => :get
  match '/customers' => 'customers#index'
  
  root:to => 'product#index'
  
    

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :description, :price, :category_id, :quantity
  belongs_to :Order
  has_one :Category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :require_sudo, :except =>[:index,:show]
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.create(params[:product])

      if @product.save
        redirect_to :action => :index
      else
        render :action => :new
      end
    end


  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

      if @product.update_attributes(params[:product])
        redirect_to :action => :index
        else
        format.html { render action: "edit" }
      end
    end


  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to :action => :index

  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div>
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div>
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div>
    <h3><%= product.name %></h3>
    <hr/>
   <%=image_tag product.img_url, :width => '100', :align => "left", :hspace => '35'%>
</div>
<div>
<p><b><u>Description :</u></b></p>
 <p id="move_over"><%= product.description %></p>
</div>
<br/>
<br/>
<div>
   <br/>
    <p>Quantity On Hand: <%= product.quantity %>,
                  Price $<%= product.price %></p>
    <%= link_to 'Add To Cart' %>
    <hr/>
</div>
    <%= link_to 'View Full Product Details', product %>
    <%= link_to 'Edit Product', edit_product_path(product) %>
<br />

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%=image_tag 'SHARK05.jpg', :width => '100', :align => "left", :hspace => '35'%><h1>All Obtuse Shark Hunting Products</h1>
<hr/>
<br/>
<br/>
<%= link_to 'Add New Product', new_product_path %>
<%= link_to 'About Obtuse Shark Hunters Incorporated', about_path%>
<%= link_to 'Contact Us', contact_path%>
<br/>
<br/>
<%= render @products %>
<br/>

app/views/products/new.html.erb
<h1>Create New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div>
    <h3><%= @product.name %></h3>
    <hr/>
   <%=image_tag @product.img_url, :width => '100', :align => "left", :hspace => '35'%>
</div>
<div>
<p><b><u>Description :</u></b></p>
 <p id="move_over"><%= @product.description %></p>
</div>
<br/>
<br/>
<div>
   <br/>
    <p>Quantity On Hand: <%= @product.quantity %>,
                  Price $<%= @product.price %></p>
    <hr/>
</div>
<%= link_to 'Back', products_path %>
<br />