config/routes.rb
ObtuseSharkHunters::Application.routes.draw do
  resources :customers

  get "customer/index"

  get "customer/show"

  get "user_views/index"

  get "user_views/show"

  get "product_user/index"

  get "product_user/show"

  resources :categories

  resources :orders

  resources :products
  
  resources :pages
  
  
  
  match '/about' => 'product_user#about'
  match '/contact' => 'product_user#contact'
  
  match '/productuser' => 'user_views#index', :as => 'user_view'
  match '/productshow/:id' => 'user_views#show', :as => 'detail', :via => :get
  match '/customers' => 'customers#index'
  
  root:to => 'product#index'
  
    

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/customer_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
    
    def new
    @customer = Customer.new
  end

  # GET /orders/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @customer = Customer.new(params[:customer])
      if @customer.save
        format.html  { redirect_to(@customer, :notice => 'Customer was successfully created.') }
      else
         format.html { render :action => "new"}
      end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @customer = Customer.find(params[:id])

      if @customer.update_attributes(params[:customer])
        redirect_to :action => :index
      else
        format.html { render action: "edit" }
      end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to :action => :index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customer/_form.html.erb
<%= form_for(@customer) do |f| %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :postalcode %><br />
    <%= f.text_field :postalcode %>
  </div>
  <div>
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :province %><br />
    <%= f.text_field :province %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/customer/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show Customer', @customer %> |
<%= link_to 'Back to All Customers', customer_path %>

app/views/customer/index.html.erb
<h1>Listing All Active Customers</h1>

<table>
  <tr>
    <th>Cust ID</th>
    <th>Order ID</th>
    <th>Name</th>
    <th>Postal Code</th>
    <th>Street</th>
    <th>City </th>
    <th>Province</th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.id %></td>
    <td><%= customer.order_id %></td>
    <td><%= customer.name %></td>
    <td><%= customer.postalcode %></td>
    <td><%= customer.street %></td>
    <td><%= customer.city %></td>
    <td><%= customer.province %></td>
    <td><%= link_to 'Show Customer Details', customer %></td>
    <td><%= link_to 'Edit Customer Details', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Customer', new_customer_path %>

app/views/customer/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customer/show.html.erb
<h1>Customer#show</h1>
<p>Find me in app/views/customer/show.html.erb</p>